[mainchain]
  # An endpoint that can query ethereum data, i.e. Infura or Alchemy like
  endpoint = ""
  chain_id = 3
  block_time = 15
  safe_block_confirmation = 2
  gateway_starting_block = 8793413
  registry = "eb4ae0dcd47e700b95c070f658d6a273b4ca3038"

# Address and block number of gateway contract on side chain
[sidechain]
  endpoint = ""
  chain_id = 2021
  block_time = 3
  safe_block_confirmation = 2
  gateway_starting_block = 26476
  registry = "eb4ae0dcd47e700b95c070f658d6a273b4ca3038"

[expired_time_secs]
  done_task = 2592000
  failed_task = 7776000
